### ISSUE TITLE
support for google.protobuf.Timestamp

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#1]
Could you please briefly articulate your vision for supporting Timestamp?  I might be able to take a shot at implementing it.

**Comment by semlanik** [comment]
Basic idea is to define special classes for each Well known type and provide built-in serializers. For some classes lwe may use existing Qt classes, e.g. Timestamp-QDateTime. But it's required to create specific [de]serialization routine that will make valid fields handling.

**Comment by R0ll1ngSt0ne** [comment]
Why introduce new types when the whole idea of protobuf is to map it to _existing_  language-specific built-in types?

**Comment by semlanik** [comment]
> Why introduce new types when the whole idea of protobuf is to map it to _existing_ language-specific built-in types?

There is not any contradiction at all. I only mentioned that in case of some classes are not fully compatible or doesn't exists and could not be bind to protobuf well-known-types need to implement them

**Comment by R0ll1ngSt0ne** [comment]
Thanks for clarifying that. But why introduce all these wrappers, such as QtProtobuf::int32,  QtProtobuf::int64? There are already standard C++ types int32_t and int64_t?

I have already encountered problems with this approach. I format int64_t - based property as follows in QML:

property.toLocaleString(...

When the property was defined as int64_t, this produced expected output as:

2,999,999

Now that the field is defined as QtProtobuf::int64, it seems to confuse QML (it doesn't recognize the value as a number) and it gets formatted as:

2999999

These type wrappers are causing issues with basic type locale formatting in QML with no clear benefit.

**Comment by R0ll1ngSt0ne** [comment]
Please ignore my last message. int64_t does not even with QML because it is unregistered.

Why not use "long long" for int64 protobuf type? QML is aware of this type and can properly apply locale formatting to it, unlike the QtProtobuf::int64 wrapper which always gets converted to string and thus cannot be locale formatted as number?

**Comment by semlanik** [comment]
We are using Qt metaobject system for reflection and serialization. And from Qt point of view there are no any difference between type aliases. That's why transparent types were introduced. Also there are some pending fixed in qt/qml to support these types

**Comment by semlanik** [comment]
c83250303c961a89eb5734b4d8c5fa731305b5fa
