### ISSUE TITLE
enum of field nums

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#108]
It would be useful to me if the field numbers were accessible via an enum somehow, similar to the _FIELD_NUMBER int's are available in the generated code for python.  
Is that something you've considered implementing?

**Comment by semlanik** [comment]
Hi @gmabey, not really, but I think it's possible to have. But probably in 0.5.0 release or later. I have a lot things to improve already and probably will be able to take care about this only closer to autumn 2020

**Comment by gmabey** [comment]
Thanks for the reply -- fall of 2020 would actually be ok the way I intend to use of this feature; it's really an optimization that can wait.
Thanks again for all of the great new developments!

**Comment by gmabey** [comment]
I'm hoping to test this and provide the requested documentation suggestion tonight!

**Comment by semlanik** [comment]
@gmabey, sorry I'm not sure why could not see your question in pull request, so answering your question here.

You should put QT_PROTOBUF_OPTIONS="FIELDENUM" to enable enums generation. And you gave me nice idea to add help to qtprotobufgenerator :) Probably will do it at some point later

**Comment by gmabey** [comment]
Yeah sorry I deleted my comment after I found that you had added
documentation to the README.md
