### ISSUE TITLE
accessing messages from QML

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#111]
It seems that I ought to be able to find the answer to this question elsewhere in the Qt documentation/forums/stackoverflow on passing C++ object to QML but have not found anything [useful] yet.

I see that with `QT_PROTOBUF_OPTIONS=QML` provided when `protoc` is invoked, the generated classes are properly registered for use in QML.   However, I'm having difficulty accessing message members from within a QML function (slot).

That is, from C++, I'm emitting a signal whose only argument is a class generated by qtprotobuf.  In the qml slot, I can see with console.log() that it's the right type, but contained in a QVariant(), as I would expect.

Could you please post a brief example of how to access the message elements?  When I try to just use a data member notation, like this:
```qml
    val = mess.ele
```
I get a qml error "Cannot assign [undefined] to QString", which doesn't surprise me, since I know QVariant doesn't have anything named `ele` ...

**Comment by semlanik** [comment]
Hi @gmabey, could you please provide extended code snipped you used? In any case here is example from address book: https://github.com/semlanik/qtprotobuf/blob/master/examples/addressbook/qml/ContactDetails.qml

The key point here is probably "import qtprotobuf.examples 1.0". These makes messages generated from protobuf package qtprotobuf.examples accessible in QML. Please be sure that you added this in your qml code.

I suppose to create simplified tutorial for protobuf and gRPC soon. Probably next week.

**Comment by gmabey** [comment]
Yes, you were right -- the `import` statement was missing.  I hope you can easily clarity the next issue that came up, but I can put together an extended code snippet if needed.

The error I'm now seeing is: `Error: Cannot assign PackageName::Event to PackageName::Event*`.

I remember seeing some Qt docs regarding memory ownership in QML, but I don't understand the implications for how I should emit a signal conveying an instance of Event.  I see two possibilities:
`emit mySignal(&event_instance)` and `emit mySignal(new PackageName::Event(event_instance)` but neither one seems quite right.  What do you recommend?

**Comment by semlanik** [comment]
When you emitting signal object passed as parameter got QML ownership by default and will be removed bu QML GC. You may use either emit mySignal(new PackageName::Event(event_instance)) way, that will behave as, lets say, event fabric or simply use QQmlEngine::setObjectOwnership(&event_instance, QQmlEngine::CppOwnership) somethere at event_instance construction point.

**Comment by gmabey** [comment]
That's very helpful thank you!

**Comment by semlanik** [comment]
No problem and thank you for help in project improvements.
