### ISSUE TITLE
paths in .cmake and .pri files include /usr/local/

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#112]
I'm using the .deb files from the official 0.3 release on ubuntu 20.04 -- thank you for providing them.

For my qmake-based project, I'm doing a `QT += protobuf` but it doesn't work out because it's looking for stuff in `/usr/local/include` and whatnot.  Doing a grep on the contents of `/usr/lib/cmake/QtProtobufProject/` reveals that it also points to `qtprotobufgen` residing in `/usr/local/bin`.

If I edit the .pri files to remove `local/`, it works fine.

If I were more knowledgeable about cmake, I might venture into making a suggestion about how to fix this, but as it is, I'll just report it.

**Comment by semlanik** [comment]
@gmabey, I fixed issues and removed broken packages. For 0.2 branch 0.2.1 version already released. Not sure how useful it will be. For 0.3 branch release packages will be available at 31.05.2020, since one more issue raised by you should be fixed before. Thank you for testing!
