### ISSUE TITLE
Won't compile with multiple string maps

### ISSUE THREAD

**Issue by anton-dutov** [semlanik/qtprotobuf#118]
**Describe the bug**
When proto contains two or more definitions ike `map<string, string>` project won't compile anymore

**To Reproduce**
modify clienttutorial messages like this (and try build)

    message EchoRequest {
      string message = 1;
      map<string, string> opts = 2;
    }

    message EchoResponse {
      string message = 1;
      map<string, string> opts = 2;
    }

**Expected behavior**
Should compile

**Environment:**
 - OS Linux
 - Version 0.3.1

**Comment by semlanik** [comment]
One of possible solution, that I see do something like:

#ifndef Q_PROTOBUF_MAP_STRING_STRING
#define Q_PROTOBUF_MAP_STRING_STRING
Q_DECLARE_METATYPEqtprotobufnamespace::duplicated_metatypes::Message1::OptsEntry)
#endif

instead of plain metatype registration. But it's quick fix and looks ugly for me.

**Comment by semlanik** [comment]
Other solution is redefine Q_DECLARE_METATYPE with type trait check of specialized function, that I like more, but it may cause Qt version incompatibility in future

**Comment by semlanik** [comment]
> Other solution is redefine Q_DECLARE_METATYPE with type trait check of specialized function, that I like more, but it may cause Qt version incompatibility in future

Ok this variant is not an option anymore. Looks like special macro definition check is the only option for this issue.

**Comment by anton-dutov** [comment]
Other way predifine most common string types like Map, List (even Vector)  etc. than skip register types on code generation,

**Comment by semlanik** [comment]
> Other way predifine most common string types like Map, List (even Vector) etc. than skip register that types on code generation

For lists it's done already and there is another issue with multi-file generation I guess. Vectors are not used in generated code.

For maps this approach is not really applicable. For each generated message, need to have huge amount of declared maps. I prefer to make it more dynamic and prevent declaration using macro.
