### ISSUE TITLE
static linking of qml plugin could be improved

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#119]
I'm building against Qt 5.12.8 and for the first time, I'm trying to [completely] statically link an application that uses QML.  I've gotten everything else (like, `libQt5QuickControls2.a` and `libqmlshapesplugin.a`) linked in (it involves using the `Q_IMPORT_PLUGIN` macro, incidentally) but now I've reached the point where it's attempting to `import QtProtobuf 0.3` and failing.

From what I can tell, `libprotobufquickplugin` is still getting created as a `.so` file (instead of a `.a`) when `-DQT_PROTOBUF_STATIC=TRUE` is given to `cmake`.  I suppose that `libprotobufquickplugin.so` (which is being installed) *could* be distributed with the app, but of course it's nicer if it's all one executable.

Also, for readers who may be dealing with the same "manual linking" issues I've been facing, the following command is your friend (assuming Qt has been installed in `/usr/`):
```bash
for f in `find /usr/qml -name *.a` `find /usr/plugins -name *.a`; do echo $f; nm $f | grep qt_static_plugin_; done
```

**Comment by semlanik** [comment]
Hi, @gmabey, yes that's correct. For plugins it's not possible to have static linking so far. Previously there was issue in Qt that cause impossibility of QML plugins static linking. I didn't check if it's possible now, but will try to integrate this feature to QtProtobuf

**Comment by gmabey** [comment]
Ok, great!  I personally don't know *how* it all works, just that if I include the other appropriate `.a` files via `target_link_libraries()` **and** give the appropriate name to `Q_IMPORT_PLUGIN` then it seems to `import` the qml module successfully -- crazy stuff!
