### ISSUE TITLE
a couple of extra install steps that seem like they could be automated

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#121]
I'm using the `3rdparty` libs provided via `--recurse-submodules` in order to build qtprotobuf for ubuntu 18.04, which is extremely helpful -- thank you.

I've found that it's necessary to perform a couple of extra steps in order to get the 3rdparty stuff installed, and I wonder whether that could be rolled into the `make install` target for qtprotobuf:
```bash
cd build/3rdparty/grpc && make install
cd build/3rdparty/microjson && make install
```

It would be one less thing to get hung up on ... a nicety.

**Comment by semlanik** [comment]
Hi @gmabey, installation of grcp was switched off for purpose. The idea of all-in-one build is to integrate QtProtobuf modern CMake way, as  submodule. In case if you want have it in your system it's better to install it standalone and use as extermal package. _Overall only tests depend on grpc_.

Regarding microjson it's linked statically and is private dependemcy for QtProtobuf. No need to install it. If there is any issue related to it, probably it's a bug.

**Comment by gmabey** [comment]
So, I gave this static build another try today given the recent commits, but I still find it necessary to `make install` microjson in order to make `QtProtobufConfig.cmake` happy enough to proceed with the build, just FYI.

**Comment by semlanik** [comment]
That's correct. I don't say that installation of microjson is not necessary at all. But there are two way how you suppose to use QtProtobuf:

1. Standalone

That means you need to build and install all dependencies by your self(including microjson) and then build and install QtProtobuf to system.

2. All-in-one

That meas you add QtProtobuf as sub-project to your project, initialize all dependencies and then build all components together.


So idea is that even if microjson is written by me it's still dependency that is not part of QtProtobuf itself and if you use standalone build, you need to install microjson manualy.

**Comment by gmabey** [comment]
Ok, that makes sense.  It just seemed non-intuitive to me, given that compilation actually succeeded, without having microjson installed, if the requirement for it was removed from the `CMakelists.txt` file for qtprotobuf.  Like, it didn't seem to actually be *needed* -- but that's fine.
