### ISSUE TITLE
Meta object features not supported for nested classes

### ISSUE THREAD

**Issue by herolover** [semlanik/qtprotobuf#122]
**Problem description**
We can't use the generator due to lots of messages like this:
```protobuf
message A {
  message B {
  }
  B b;
}
```

Generator produces errors:
`... Meta object features not supported for nested classes ...`

But it's very conveniently to define messages inside other messages and it's totally OK with protobuf. So it's very strange to forbid it.

**Suggestion/solution**
It would be great, if you allow such behavior. I think nested classes could be generated outside its source parent class and it won't be a problem.

**Comment by semlanik** [comment]
@herolover unfortunatelly it's not possible to have nested Q_OBJECT based classes in Qt. I thought about possible solution like definition of nesting namespace with class name. But all this stuff looks like hacks. From interface design I personally don't understand the purpose of nesting. It looks like interface-level encapsulation, that to be honest is not applicable for interfaces. So probably I will back to namespaces-based solution later.

**Comment by semlanik** [comment]
@herolover, I thought a little about solution, so I think it might work as following for your example:

message A {
  message B {
  }
  B b;
}

Proposed generated code:

nested {
namespace A {
class B {
Q_OBJECT
...
};
}
}

class A {
Q_OBJECT
...
nested::A::B m_b; //and all related methods
};

If this approach looks good for you, I will try to implement int in 0.4.0.

**Comment by herolover** [comment]
I think it's acceptable. Thank you! We will continue following your lib and will try it again when the feature is done.

**Comment by semlanik** [comment]
@herolover, basic implementation is complete. You may try from source or wait until release 0.4.0 packages published. Overall types are located in <containing class name>_QtProtobufNested namespace, but should be used with original namespaces chain (I placed "using" constuction to access nested messages easier)

**Comment by herolover** [comment]
Awesome! Thank you! Will check it on the next week.
