### ISSUE TITLE
issues with static linking continue

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#129]
I wonder what I'm still doing wrong, as I see that #119 is closed, yet I'm still failing to get a compiled application to run.  Here's what I changed.

* I added this line to my `CMakelists.txt` file:
```cmake
target_link_libraries(MyAppName PUBLIC /usr/qml/QtProtobuf/libprotobufquickplugin.a QtProtobuf QtProtobufWellKnownTypes)
```
Then, in my `main.cpp`:
```c++
Q_IMPORT_PLUGIN (QtProtobufQuickPlugin);
```
which then successfully builds.  However, when I execute I see:
```bash
QQmlApplicationEngine failed to load component
qrc:/main.qml:17 Type Viewer unavailable
qrc:/Viewer.qml:200 Type EventMetaDataPane unavailable
qrc:/EventMetaDataPane.qml:3 module "QtProtobuf" is not installed

Segmentation fault (core dumped)
```
Any hints would be appreciated.

Looking at `/usr/qml/*/`, seems as if the `QtProtobuf/` directory is missing a `plugins.qmltypes` file that all of the other directories have ...

**Comment by semlanik** [comment]
@gmabey, sorry docs for static quick plugin will be published later. I already wrote usage instruction in doxygen. But segfault a little disappointing me. If you could take core dump it would be very helpful for analysis. Anyway back to instructions:

For statically built QtProtobuf it's neccssary to link `protobufquickplugin` target manually:
 CMakeLists.txt:
 ```
 ...
if(QT_PROTOBUF_STATIC)
target_link_libraries(${TARGET} PRIVATE QtProtobufProject::protobufquickplugin)
endif()
...
```
To make QtProtobuf QML plugin visible in QML, call Q_PROTOBUF_IMPORT_QUICK_PLUGIN() macro:
```
int main(int argc, char *argv[]) {
    ...
    QtProtobuf::qRegisterProtobufTypes();
    Q_PROTOBUF_IMPORT_QUICK_PLUGIN()
    ...
}
```

**Comment by gmabey** [comment]
Yes, that seems to have done it!  Thank you!
