### ISSUE TITLE
Client spam when server is not running

### ISSUE THREAD

**Issue by 0x460** [semlanik/qtprotobuf#13]
Reproduce:

1. Start simplechat client
2. Attempt to login

You'll see the application repeatedly printing `qtprotobuflog: "messageList" call "qtprotobuf.examples.SimpleChat" subscription finished:  "Connection refused"`.

Expected:

A single error message should be sufficient.

Edit: Using Qt version 5.14.

**Comment by semlanik** [comment]
Hi, could you please specify Qt version you used

**Comment by semlanik** [comment]
Overall subscriptions currently have auto-recovery mechanism inside, without possibility to cancel it. That's why while server inaccessibility it's reconnecting continuously. Will be improved soon

**Comment by semlanik** [comment]
6007ecc6
