### ISSUE TITLE
"transparent" types break "lvalue" and "rvalue" concepts, introducing errors

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [semlanik/qtprotobuf#14]
Using "transparent" type to define fields of output C++ Qt classes introduces bugs and potential pitfalls - since it **allows a value to be assigned to a _getter_ function call**. Here is some code to illustrate:

```
transparent<int> m;

transparent<int> GetM() { return m; }

int n;

int GetN() { return n; }

int main()
{
    std::cout << "Hello World!\n";

    GetM() = 25; // No warning or compiler error
    GetN() = 26; // error C2106: '=': left operand must be l-value 
}
```

Assigning a value to the transparent value getter appears legal and does not produce a warning or an error. This leads to logic errors since usage of setters is no longer enforced - and the assignment does not produce an expected result.

For us, this is a big issue. We are trying to replace a bunch of plain C structs with proto-generated C++ Qt classes. Simply replacing struct field references with class getters results in hard-to-detect errors - since assigning a value to a getter is legal.

**Comment by semlanik** [comment]
Hi, thanks for pointing this issue.
Have no ideas how to restrict l-value usage for transparent types, except to restriction of copy-constructors, but it's impossible from code design perspective. Other possible fix is to make getters return value constant, but it won't prevent of manual types usage in consumer code. If you know good way to fix this behavior please provide fix. Thank you!
