### ISSUE TITLE
Default values are ignored in GRPC Subscriptions

### ISSUE THREAD

**Issue by rapgenic** [semlanik/qtprotobuf#142]
**Describe the bug**
Default values like 0 for numbers sent through subscriptions do not update the object passed when registering the subscription.

**To Reproduce**
1. Make a server that sends through a stream a BoolValue alternating true and false
2. Register a subscription with a return object
3. When true is received the return object value doesn't become false anymore

**Expected behavior**
Updating the return object.

**Environment:**
 - OS: linux
 - Version 3add1f886c139b15c874e33984577584483a4aef

**Additional context**
When default values like 0 for numbers are sent via protobuf through a stream, by design of the protocol an empty message is sent. This means that no serialisation is performed and the object is never updated.

**Comment by semlanik** [comment]
@rapgenic thanks for pointing this issue. It looks like 'optional' field support is required in QtProtobuf at this point as well. Will fix basic usecase for simple types, but repeated fields will work for append only.
