### ISSUE TITLE
Additional cmake helps

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#150]
I'm still learning `cmake` but now have a build environment where I'm trying to link against a version of Qt that was installed in `/opt` instead of using the distribution (ubuntu 20.04) provided Qt.

I have found it necessary to add these lines to my `CMakeLists.txt` file, and if they are correct, I would like to suggest that they be added to the project's `README.md` for all to enjoy:
```cmake
find_package(QtProtobufProject CONFIG REQUIRED COMPONENTS QtProtobuf QtProtobufWellKnownTypes)
target_include_directories(${TARGET} PRIVATE $<TARGET_PROPERTY:${QT_PROTOBUF_PROJECT}::QtProtobuf,INTERFACE_INCLUDE_DIRECTORIES>)
target_link_libraries(${TARGET} PUBLIC
  $<TARGET_PROPERTY:${QT_PROTOBUF_PROJECT}::QtProtobuf,IMPORTED_LOCATION_NOCONFIG>
  $<TARGET_PROPERTY:${QT_PROTOBUF_PROJECT}::QtProtobufWellKnownTypes,IMPORTED_LOCATION_NOCONFIG>)
```

However, it seems like the `target_include_directories()` and `target_link_libraries()` calls should somehow happen automatically, like with the `find_package()` call.  Am I missing something here?

**Comment by semlanik** [comment]
Hi @gmabey , in case if you avoid ```qtprotobuf_generate``` usage some how, you probably need to link QtProtobuf libraries manually. It's not necessary to target_include_directories in case if you use not target libraries paths, but targets them selves in ```target_link_libraries``` function. As summary, code bellow should work for you:

```
target_link_libraries(${TARGET} QtProtobuf::QtProtobuf QtProtobuf::QtProtobufWellKnownTypes)
```

Will add few words about manual linking to README for next release.
