### ISSUE TITLE
quick plugins are getting installed to the wrong directory somehow

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#151]
When I build QtProtobuf 0.4.0 using this `cmake` invocation:
```
cmake .. -DQT_PROTOBUF_MAKE_TESTS=FALSE -DQT_PROTOBUF_MAKE_EXAMPLES=FALSE -DCMAKE_INSTALL_PREFIX=/opt/Qt5.14.2/5.14.2/gcc_64
```
somehow `qt_lib_protobuf.pri` `libprotobufquickplugin.so` and others are getting installed in the path of my distribution (ubuntu 20.04) Qt, as shown in the stdout of `make install`:
```
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake/QtProtobufProject/parsemessages.go
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake/QtProtobufProject/ProtobufLookup.cmake
-- Up-to-date: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_protobuf.pri
-- Installing: /usr/lib/x86_64-linux-gnu/qt5/qml/QtProtobuf/libprotobufquickplugin.so
-- Set runtime path of "/usr/lib/x86_64-linux-gnu/qt5/qml/QtProtobuf/libprotobufquickplugin.so" to ""
-- Installing: /usr/lib/x86_64-linux-gnu/qt5/qml/QtProtobuf/qmldir
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQtGrpc.so.0.4.0
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQtGrpc.so
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/include/QtGrpc/qabstractgrpcchannel.h


-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake/QtProtobufProject/QtGrpcConfig.cmake
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake/QtProtobufProject/gRPCLookup.cmake
-- Up-to-date: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_grpc.pri
-- Up-to-date: /usr/lib/x86_64-linux-gnu/qt5/qml/QtGrpc/libgrpcquickplugin.so
-- Up-to-date: /usr/lib/x86_64-linux-gnu/qt5/qml/QtGrpc/qmldir
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/bin/qtprotobufgen
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake/QtProtobufProject/qtprotobufgenTargets.cmake
-- Installing: /opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake/QtProtobufProject/qtprotobufgenTargets-noconfig.cmake
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQtProtobufWellKnownTypes.so.0.4.0
-- Up-to-date: /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQtProtobufWellKnownTypes.so
```

Is there another option that I need to pass to `cmake`??

**Comment by semlanik** [comment]
Hi @gmabey , here is the tricky point. While compilation you used not Qt installed in /opt/Qt5.14.2/5.14.2, but system one. Paths for installation are taken from ```qmake``` that was used during the compilation.  So to achive what you expect, guess you need add -DCMAKE_PREFIX_PATH=/opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake to configuration line.

```
cmake .. -DQT_PROTOBUF_MAKE_TESTS=FALSE -DQT_PROTOBUF_MAKE_EXAMPLES=FALSE -DCMAKE_INSTALL_PREFIX=/opt/Qt5.14.2/5.14.2/gcc_64 -DCMAKE_PREFIX_PATH=/opt/Qt5.14.2/5.14.2/gcc_64/lib/cmake
```

That trick will give preference to manually installed Qt instead of system one and use correct installation paths.

Please let me know if this would work for you.

**Comment by gmabey** [comment]
Hi @semlanik ,

Thank you for the reply.  Unfortunately, this change did not fix my problem; I already had CMAKE_PREFIX_PATH set as an exported env variable; that's how it used 5.14 in the first place.  Putting it on the `cmake` command line did not affect the behavior.

Glen

**Comment by semlanik** [comment]
Hi @gmabey, I checked your scenario in my environment, and following works for me:

make .. -DQT_PROTOBUF_MAKE_TESTS=FALSE -DQT_PROTOBUF_MAKE_EXAMPLES=FALSE -DCMAKE_INSTALL_PREFIX=/opt/Qt5.14.2/5.14.2/gcc_64 -DCMAKE_PREFIX_PATH=/opt/Qt5.14.2/5.14.2/gcc_64

Important part here is to provide CMAKE_PREFIX_PATH to whole Qt installation ```/opt/Qt5.14.2/5.14.2/gcc_64
```, but not only cmake files. So ```find_program("qmake")``` will look up inside /opt/Qt5.14.2/5.14.2/gcc_64/bin as well.

**Comment by gmabey** [comment]
@semlanik hmm that's very strange -- I'm running cmake 3.16.3, that comes with Ubuntu 20.04.  Is there any chance it's a `cmake` bug?

**Comment by semlanik** [comment]
@gmabey, I have feeling that it might be "expected behavior" for newest cmake. I have one idea, let me check it and I will back with patch set.

**Comment by semlanik** [comment]
@gmabey, I added prioritized lookup for non-system paths to build procedure https://github.com/semlanik/qtprotobuf/pull/154. If it doesn't help I guess you need to check carefully you environment and Qt distribution you use for build.
