### ISSUE TITLE
Subscription memory "leaks"

### ISSUE THREAD

**Issue by rapgenic** [semlanik/qtprotobuf#157]
**Describe the bug**
Whenever a subscription cannot connect to the server, new subscription objects get created indefinitely quickly filling the memory

**To Reproduce**
1. Create a channel that is not able to connect to the server
2. Subscribe to a stream
3. Memory starts filling

**Environment:**
 - OS: linux
 - Version 0.5.0

**Additional context**
I think the problem lies in the `error` callback handler in `qabstractgrpcclient.cpp` line 152. Whenever the callback is called a new call to the underlying channel's subscribe implementation is performed, where i suspect a few leaks may hide.

Another thing that I noticed is that in the http implementation of subscriptions the event finished is never called on the QGrpcSubscription object whenever the connection closes, is this related in any way?

I stumbled across this problem while testing my pull request #147 but i found that is present on your default implementation too, that's why i opened the issue, also because i have not found yet where is the source of the problem.

**Comment by semlanik** [comment]
Hi @rapgenic , I think you are right. Will fix shortly. Lambda is created continuously there in case of error.

**Comment by rapgenic** [comment]
I think applying this patch might be useful too, which makes sure that all `shared_ptr` pointing to the subscription object are actually deleted when the subscription emits `finished`. In fact as it is now, the lambda callback attached to the error signal is not deleted so the shared_ptr never destroys the subscription object

```
diff --git a/src/grpc/qabstractgrpcclient.cpp b/src/grpc/qabstractgrpcclient.cpp
index 18e7ee5..500e6c8 100644
--- a/src/grpc/qabstractgrpcclient.cpp
+++ b/src/grpc/qabstractgrpcclient.cpp
@@ -149,14 +149,15 @@ QGrpcSubscriptionShared QAbstractGrpcClient::subscribe(const QString &method, co
             return *it; //If subscription already exists return it for handling
         }
 
-        connect(subscription.get(), &QGrpcSubscription::error, this, [this, subscription](const QGrpcStatus &status) {
+        auto errorConnection = std::make_shared<QMetaObject::Connection>();
+        *errorConnection = connect(subscription.get(), &QGrpcSubscription::error, this, [this, subscription](const QGrpcStatus &status) {
             qProtoWarning() << subscription->method() << "call" << dPtr->service << "subscription error: " << status.message();
             error(status);
             dPtr->channel->subscribe(subscription.get(), dPtr->service, this);
         });
 
         auto finishedConnection = std::make_shared<QMetaObject::Connection>();
-        *finishedConnection = connect(subscription.get(), &QGrpcSubscription::finished, this, [this, subscription, finishedConnection]() mutable {
+        *finishedConnection = connect(subscription.get(), &QGrpcSubscription::finished, this, [this, subscription, finishedConnection, errorConnection]() mutable {
             qProtoWarning() << subscription->method() << "call" << dPtr->service << "subscription finished";
             auto it = std::find_if(std::begin(dPtr->activeSubscriptions), std::end(dPtr->activeSubscriptions), [subscription](QGrpcSubscriptionShared activeSubscription) {
                return *activeSubscription == *subscription;
@@ -166,6 +167,7 @@ QGrpcSubscriptionShared QAbstractGrpcClient::subscribe(const QString &method, co
                 dPtr->activeSubscriptions.erase(it);
             }
             QObject::disconnect(*finishedConnection);
+            QObject::disconnect(*errorConnection);
             subscription.reset();
         });
```

Please forgive me if i don't open a pull request, but my current source tree is a bit messy and given the small nature of the patch I hope it doesn't bother you too much

**Comment by semlanik** [comment]
@rapgenic , I applied same fix. But problem was deeper in Http2 channel implementation. Did fix as well :)

**Comment by rapgenic** [comment]
@semlanik Thank you very much.

Also what about adding a little timeout befor calling subscribe again on the error callback? That would prevent a general slowdown of the application whenever a persistent error occurs on the connection.

**Comment by semlanik** [comment]
@rapgenic https://github.com/semlanik/qtprotobuf/issues/159 created separate task for that :)
