### ISSUE TITLE
Compatibility with plain C++ protobuf messages.

### ISSUE THREAD

**Issue by hosaka** [semlanik/qtprotobuf#162]
*Question*
Is it possible to serialize an to binary from protobuf message in C++, and deserialize it in QtProbuf? Of course, the .proto files used to generate Qt/C++ classes are the same.

**Additional context**
I have a project that sends messages from lower level library, messages go through a redis instance and retrieved at a Qt application where QtProtobuf is used. There's no issues using JSON, but when I use binary format I get the following:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  Container is less than required fields number. Deserialization failed
```

I am also using PySide2/Shiboken2 to generate python wrappers on top of QtProtobuf generated code, which call the underlying serialize/deserialize functions using QByteArray. If I create two identical objects in C++ and Qt with Python and serialize them to binary, I can see that they are slightly different but unfortunately don't have the knowledge to find the root of the problem.

In python:
```python
    conf = Test.Device.Config()
    conf.setVersion(42)
    serial = Test.Protobuf.Serializer(Test.Protobuf.Serializer.TYPE_PROTOBUF)
    payload = conf.serialize(serial)
    # payload = {QByteArray: 2} b'\x08*'
    # I can deserialize the payload back to Test.Device.Config with no problem
```
In c++
```c++
        auto *payload = new Test::Device::Config();
        payload->set_version(42);
        std::string data;
        payload->SerializeToString(&data);
        // data = {std::__cx11::string} "\b*"
        // this is then shoved into a redis stream, and fails to deserialize in Python
```

**Comment by semlanik** [comment]
Hi @hosaka , QtProtobuf is fully compatible with binary protobuf. It's the idea of protobuf it self. Could you please show me you .proto file for the message you mentioned? BTW it's quite strange that in native c++ non-empty data gave you empty buffer:
```
    payload->SerializeToString(&data);
    // data = {std::__cx11::string} "\b*"
```

**Comment by hosaka** [comment]
@semlanik Sure, the package name was renamed, but here it is:
```
syntax = "proto3";

package Pick.Device;

import "Content.proto";

message Config {
  uint32 version = 1;
  repeated Pick.Content.Schedule schedules = 2;
}
```
When I serialize to json everything seems fine. Here's a screenshot from the debug
![Screenshot from 2020-09-26 11-01-17](https://user-images.githubusercontent.com/171876/94327689-b0fb2a00-ffe7-11ea-93c3-53763c4a4d0d.png)

At least that's not an issue with qtprotobuf, something else is broken elsewhere.

**Comment by hosaka** [comment]
I went over everything again, I think my proto file had different fields in the Qt and C++ projects, due to my mistake and that caused issues. I can ser/deser more complex data now between QtProtobuf and C++. I am not very familiar with protobuf, but doesn't `\b*` imply that the value is `42`? If I look at it in ASCII.

**Comment by semlanik** [comment]
@hosaka , I didn't recognize the output format from previous messages. Yes, looks like format is correct, and `\b*` is explicitly `082a` in hex. This message should be parsed correctly in case if generated code is match. Probably issue is conversion between QByteArray and std::string when you pass it?

**Comment by hosaka** [comment]
@semlanik After making sure the same proto was used on both ends, I've had no problems. I can deserialize the messages at the Qt side now. Thank you for your help!
