### ISSUE TITLE
GrpcChannel tests not working anymore

### ISSUE THREAD

**Issue by rapgenic** [semlanik/qtprotobuf#172]
Hi @semlanik,

while testing the new commits I noticed that the tests I wrote aren't working anymore and I suspect the cause is the removal of the following lines from the `tests/test_grpc/CMakeLists.txt`

```
if (QT_PROTOBUF_NATIVE_GRPC_CHANNEL)
    target_compile_definitions(qtgrpc_test PRIVATE QT_PROTOBUF_NATIVE_GRPC_CHANNEL)
    target_compile_definitions(qtgrpc_secure_test PRIVATE QT_PROTOBUF_NATIVE_GRPC_CHANNEL)
endif()
```

That happened on commit: facaba67f2bb255211e9373ee7e2674596843318

**Comment by rapgenic** [comment]
Another thing I discovered is that the CI does not automatically run the tests with the flag QT_PROTOBUF_NATIVE_GRPC_CHANNEL. I don't know how the CI works, so I'm only reporting it to you

**Comment by semlanik** [comment]
Hi @rapgenic ,

I add public compile definition to QtGrpc, that should work. Let me check first. I didn't enable these tests on CI because at some point travis start exit by timeout. For sanity check I probably will omit QT_PROTOBUF_NATIVE_GRPC_CHANNEL for now. But for master branch will enable it after some timing tests. Thanks!

**Comment by semlanik** [comment]
@rapgenic I checked locally seems QT_PROTOBUF_NATIVE_GRPC_CHANNEL works as expected and I see tests passed. Did you enabled QT_PROTOBUF_NATIVE_GRPC_CHANNEL in your build setup? Keep in mind that I made this CMake property cached and it might not be enabled without reconfiguration.

**Comment by rapgenic** [comment]
@semlanik,

It seems that my system is the problem, even though I cannot identify what it is...

I'll try to investigate a bit more but right now I have no clue.

**Comment by rapgenic** [comment]
I found something quite strange using cmake `watch_variable`:

the value of QT_PROTOBUF_NATIVE_GRPC_CHANNEL changed when building tests, because the `find_package` call loaded the `QtProtobufProjectConfig.cmake` file from another project in a different folder, that includes qtprotobuf, where that variable actually has a different value...

How is it possible? Is there any form of caching outside the local build folder?

**Comment by rapgenic** [comment]
Ok I think I might have found the problem.

I observed that deleting the `~/.cmake` folder allowed me to build again everything without error. According to cmake's help (https://cmake.org/cmake/help/v3.9/manual/cmake-packages.7.html#id21) in that folder are registered the user packages that are published with the `export` function.

Qtprotobuf actually uses this function to export itself as a package, and I think that after building it in another place, it registered itself as **the** qtprotobuf package, so when building the tests in another location, `find_package` does not include the local version of the library, but instead the other one which might be anywhere else in the system with possibly a different configuration.

**Comment by semlanik** [comment]
Probably I should add if(TARGET ...) check before find_package in tests and examples.
