### ISSUE TITLE
Feature: miscrojson as static built-in

### ISSUE THREAD

**Issue by anton-dutov** [semlanik/qtprotobuf#173]
**Problem description**
1. Another unnecessary library in the system
2. Repository not provided, potentialy dependency tracking issue

**Suggestion/solution**
microjson should be static built-in

**Comment by semlanik** [comment]
Hi @anton-dutov, that what I tried to do in last few commits related to build procedure. Looks like smt went wrong. Let me check and I will back. BTW do you use static or dynamic linking across project?

**Comment by anton-dutov** [comment]
i tried examples with deb package provided with release v0.5
Using dynamic link (shared libs)

**Comment by anton-dutov** [comment]
Also i tried lastest master

    ldd libQtProtobuf.so.0.5.0 | grep microjson
        libmicrojson.so.0.1.0 => /lib/libmicrojson.so.0.1.0 (0x00007f16f6a8c000)

**Comment by anton-dutov** [comment]
So master branch won't build any client examples, when i switch to v0.5.0 and try static build libmicrojson linkked as shared lib too

**Comment by semlanik** [comment]
Ok, now I see context of this issue. Probably that was already fixed for upcomming 0.6.0. Please look at facaba67f2bb255211e9373ee7e2674596843318 . The idea is to identify whenever microjson is available in the system or not. If not it will be linked statically and/or installed in the system by QtProtobuf it self

**Comment by anton-dutov** [comment]
Now microjson in build tree, but linked as shared lib

**Comment by anton-dutov** [comment]
Tried 808188a53b6f4e2f503e76764cf27c6c62edc0a9, seems fine

**Comment by semlanik** [comment]
Yeah, need also fix static build on Windows and we are done :D

**Comment by semlanik** [comment]
a28080e4805d74c90a858fc1bb7049a5359ae683
