### ISSUE TITLE
build error on master 

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#176]
This morning I checkout out master and am attempting to build on ubuntu 20.04, but I see this error:
```
CMake Error at src/protobuf/CMakeLists.txt:21 (find_package)
  Could not find a package configuration file provided by "microjson" with
  any of the following names:
    microjsonConfig.cmake
    microjson-config.cmake
```
and sure enough, `microjsonConfig.cmake.in` exists but the others do not.  Am I missing a build step here?

**Comment by semlanik** [comment]
@gmabey probably you missed microjson submodule intialization and update?

**Comment by hesa2020** [comment]
> @gmabey probably you missed microjson submodule intialization and update?

If you look it isnt part of the master branch anymore:

https://github.com/semlanik/qtprotobuf/tree/master/3rdparty

**Comment by gmabey** [comment]
Yes, you're right -- seems there was a relocation of that submodule, and I did not track it appropriately.
