### ISSUE TITLE
include could not find load file QtProtobufWellKnownTypesConfig.cmake

### ISSUE THREAD

**Issue by kwakobo** [semlanik/qtprotobuf#183]
I have added QtProtubuf as a submodule and added it to my cmake project:

```cmake
...
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(QT_PROTOBUF_MAKE_TESTS OFF)
set(QT_PROTOBUF_MAKE_EXAMPLES OFF)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/lib/qtprotobuf)
find_package(QtProtobufProject CONFIG COMPONENTS QtProtobuf QtGrpc QtProtobufWellKnownTypes REQUIRED)
find_package(Qt5 COMPONENTS Core Network REQUIRED)

file(GLOB PROTO_FILES ABSOLUTE "${CMAKE_CURRENT_SOURCE_DIR}/src/interface.proto")

add_executable(${TARGET}
    main.cpp)
qtprotobuf_generate(TARGET ${TARGET}
OUT_DIR ${CMAKE_CURRENT_BINARY_DIR}/generated
PROTO_FILES ${PROTO_FILES})

target_link_libraries(${TARGET}
    Qt5::Core
    Qt5::Network)
```

However, cmake throws the following error:
```
-- Generate Qt header for QGrpcSubscription
-- Generate Qt header for QGrpcUserPasswordCredentials
-- Generate Qt header for QtProtobufQtTypes
-- Enabled QML generation for QtProtobufQtTypes_qtprotobuf_gen
-- Enabled FOLDER generation for QtProtobufQtTypes_qtprotobuf_gen
-- Using doxygen to generate documenation: C:/Program Files/doxygen/bin/doxygen.exe
CMake Error at C:/Users/User/git/build-portal-MSVC_Qt_5_12_10/lib/qtprotobuf/QtProtobufProjectConfig.cmake:5 (include):
  include could not find load file:

    C:/Users/User/git/build-portal-MSVC_Qt_5_12_10/lib/qtprotobuf/QtProtobufWellKnownTypesConfig.cmake
Call Stack (most recent call first):
  CMakeLists.txt:16 (find_package)
```

If I do not add `QtProtobufWellKnownTypes`, I am able to generate source files from my .proto file. I want to be able to `import "google/protobuf/empty.proto";` as described in the [wiki](https://semlanik.github.io/qtprotobuf/group__QtProtobufWellKnownTypes.html).

Any help would be appreciated.

**Comment by kwakobo** [comment]
Ahh. I just found this [comment](https://github.com/semlanik/qtprotobuf/blob/a28080e4805d74c90a858fc1bb7049a5359ae683/CMakeLists.txt#L76):
```cmake
if(NOT WIN32)#TODO: There are linking issues with windows build of well-known types...
    add_subdirectory("src/wellknowntypes")
endif()
```

I'm assuming this means QtProtobufWellKnownTypes is not yet supported on Windows. Are there any plans for this on Windows?

**Comment by semlanik** [comment]
Hi @kwakobo , sorry for that, but wellknown types are disabled for WIN32 platforms. There is an issue with linking there, that probably I did solve already, but didn't test. 

What I could suggest is comment out check here:
https://github.com/semlanik/qtprotobuf/blob/a28080e4805d74c90a858fc1bb7049a5359ae683/CMakeLists.txt#L76

And see if it's able to build and link wellknown types.

**Comment by semlanik** [comment]
Should work now
