### ISSUE TITLE
building and using qtprotobuf within a docker container

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#184]
My host OS is ubuntu 20.04 (which comes with Qt 5.12.8), but I need to compile my application against Qt 5.15 and run it in a docker instance.  So, first I compiled Qt using this `configure` line:
```bash
./configure -prefix /usr -nomake examples -nomake tests -c++std c++17 -no-dbus
make -j 24
```
Then I built `qtprotobuf` in the docker image with 
```bash
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DQT_PROTOBUF_MAKE_TESTS=FALSE -DQT_PROTOBUF_MAKE_EXAMPLES=FALSE
make -j 24 && make install
```
Which all went smoothly.  And, if I start a container based on that instance, I can see all of the files properly installed:
```bash
$ docker run -it run-in-qt5.15_build
root@3fee3976e1f4:/# ls -l /usr/qml/QtGrpc/libgrpcquickplugin.so  /usr/lib/x86_64-linux-gnu/cmake/QtProtobufProject/QtProtobufConfig.cmake  /usr/bin/qtprotobufgen /usr/lib/x86_64-linux-gnu/libQtProtobufWellKnownTypes.so.0.5.0
-rwxr-xr-x 1 root root  739360 Dec 29 00:01 /usr/bin/qtprotobufgen
-rw-r--r-- 1 root root    2073 Dec 29 00:00 /usr/lib/x86_64-linux-gnu/cmake/QtProtobufProject/QtProtobufConfig.cmake
-rw-r--r-- 1 root root 3417864 Dec 29 00:01 /usr/lib/x86_64-linux-gnu/libQtProtobufWellKnownTypes.so.0.5.0
-rw-r--r-- 1 root root  180240 Dec 29 00:01 /usr/qml/QtGrpc/libgrpcquickplugin.so
root@3fee3976e1f4:/# which qmake
/usr/bin/qmake
root@3fee3976e1f4:/# qmake --version
QMake version 3.1
Using Qt version 5.15.2 in /usr/lib
```
However, now as I try to build my application, I get a `qtprotobuf` related error stemming from the line in my `CMakeLists.txt` file that reads:
```cmake
find_package(QtProtobufProject CONFIG REQUIRED COMPONENTS QtProtobuf QtProtobufWellKnownTypes)
```
The errors look like this:
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/QtProtobufProject/GeneratorConfig.cmake:7 (set_property):
  set_property could not find TARGET qtprotobufgen.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/QtProtobufProject/QtProtobufProjectConfig.cmake:5 (include)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/QtProtobufProject/QtProtobufConfig.cmake:6 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/QtProtobufProject/QtProtobufProjectConfig.cmake:5 (include)
  CMakeLists.txt:135 (find_package)
```

I'm sorry to be posting this question here, as it might well be just a `cmake` usage error, but I sure haven't made any headway on this issue today, and the error message sure hasn't helped me turn up any useful leads on StackOverflow or anything.

I'm hoping that someone will know enough about `cmake` *and* this project that they can easily determine what I'm missing here, as `qtprotobufgen` (and all of the supporting `.cmake` files) seem to be installed properly, already.

**Comment by semlanik** [comment]
It's regression of this commit https://github.com/semlanik/qtprotobuf/commit/1ceacf28b0060c4d053137290f0bc5ba0c44019a

**Comment by gmabey** [comment]
Yes, that did resolve the issue I was having -- thank you for the quick fix.
