### ISSUE TITLE
crash on multi-threaded initialization

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#19]
It looks to me that the static data member of QProtobufSerializerPrivate, "SerializerRegistry handlers" needs to be protected by a mutex.  My program frequently crashes when two separate threads both instantiate a QProtobufSerializer at the same time.  Better yet, have you considered using Q_GLOBAL_STATIC?  You *might* still need a mutex (I would use Q_GLOBAL_STATIC_WITH_ARGS to give it a QMutex::Recursive behavior) depending on whether you decide to change how "handlers" gets populated.  

I think that the primary advantage of Q_GLOBAL_STATIC lies in its ability to preserve the uniqueness of "handlers" across shared library (DLL) boundaries.

**Comment by semlanik** [comment]
Thanks, for pointing issue. Will analyse and back, but probably we missed it in latest changes
