### ISSUE TITLE
headers for well-known types no longer seem to be installed with libqtprotobuf-dev

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#197]
On ubuntu 20.04, I'm just today updating from 0.5.0 to master.  I successfully built .deb's for libqtprotobuf{,-dev}, but now my application build is failing
```bash
$ cmake ..
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "QtProtobuf::ProtobufWellKnownTypes" includes non-existent
  path

    "/usr/include/QtProtobuf/google/protobuf"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
and sure enough, 0.5.0 installed files under that path, but `master` does not.  Is it possible I missed a new `include()` required in my cmake file?  I'm following the directions in the README.md ...

**Comment by semlanik** [comment]
@gmabey , thanks for pointing the issue. I broke a lot while refactoring the cmake rules.
