### ISSUE TITLE
compile error on generated code

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#199]
Using today's version of `master`, I'm getting compile errors on the generated `.qpb.cpp` file (like 10 of them) like this:

```
MyFile.qpb.cpp:17:12: error: could not convert ‘{{1, 1}, {2, 2}, {3, 3}, {4, 4}, {5, 5}}’ from ‘<brace-enclosed initializer list>’ to ‘const QProtobufPropertyOrdering’ {aka ‘const std::unordered_map<int, QtProtobuf::PropertyOrderingInfo>’}
   17 |     ,{5, 5}};
      |            ^
      |            |
      |            <brace-enclosed initializer list>
```

Just in case you weren't aware ...

**Comment by semlanik** [comment]
Hi @gmabey , did you regenerate the code you mentioned in the issue using recent generator or it's the code generated previously? I broke backward compatibility here https://github.com/semlanik/qtprotobuf/commit/47b1807ae15e1bf897b9a9b2b1296d5550f8dea2 , so the code generated using the old generator is not compatible with the master branch anymore.
