### ISSUE TITLE
on Ubuntu 19.04 I had to append -lpthread to some of the tests/examples

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#2]
In building qtprotobuf, I had to explicitly append a "-lpthread" to some of the build lines (like for test_protobuf) in order to get them to successfully link.  It think that's a gcc 8 thing.

**Comment by semlanik** [comment]
We merged changes please check on clean build

**Comment by gmabey** [comment]
Yes you're right that did fix it.
