### ISSUE TITLE
qmlRegisterType() didn't used to be necessary, seems to be now

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#201]
On `master`, I now find that if I do not invoke `qmlRegisterType<MyPackage::MyMessage>()` that my QML statements that `import` MyPackage fail.  It didn't used to be that way -- am I missing something?

And yes, in my `main()` function (right off the bat) I do `QtProtobuf::qRegisterProtobufTypes()`

**Comment by ddobrev** [comment]
I agree, having to register each and every type by hand would be so inconvenient that it would question the feasibility of the library to begin with.

**Comment by semlanik** [comment]
I guess this happens in release builds only :) That's my stupidity:
https://github.com/semlanik/qtprotobuf/commit/bf72e53e1840fb37d8d1ee2a51bcfbd3aee0b525#diff-3c3c2ede01f8ade048a62253b725c876bb9397f172dc93dcdb3426bc90167f42R374

Q_ASSERT is expanded to nothing in release builds.
