### ISSUE TITLE
upload large files

### ISSUE THREAD

**Issue by tangyoha** [semlanik/qtprotobuf#209]
*Question*
How to use the api generated by qtprotobuf to make a program to upload large files
**Additional context**

**Comment by tangyoha** [comment]
like that:
```cpp
rpc SendFile(stream SendFileRequest) returns (SendFileResponse) {}


//and gen
 QtProtobuf::QGrpcStatus SendFile(const httpapi::SendFileRequest &arg, const QPointer<httpapi::SendFileResponse> &ret);

//How to use this generated api?
//I want to send the file in pieces
```

**Comment by tangyoha** [comment]
my proto file:
```cpp
// 聊天
message ChatMessage {
  enum ContentType {
        Unknown = 0;
        Text = 1;
        Image = 2;
        Video = 3;
    };
    uint64 timestamp = 3; 
    bytes content = 4;
    ContentType type = 5;
    string from = 6;
    string to = 7;
}

message ChatMessageRequest {
    uint64 seq = 1;
    uint64 totalBlock = 2;
    uint64 splitSeq = 3;
    ChatMessage message = 4;
}

message ChatMessageResponse {
        uint64 seq = 1;
}

service HttpApi {
    rpc SendChatMessage(stream ChatMessageRequest) returns (stream ChatMessageResponse) {}
    rpc ChatMessageLoop(stream None) returns (stream ChatMessageRequest) {}
}
```

and my cpp code:
```cpp
for (; blockIndex < totalblockNum - 1; ++blockIndex) {
			ChatMessage message(static_cast<quint64>(QDateTime::currentMSecsSinceEpoch()), imgData.mid(blockIndex * (1024 * 1024), 1024 * 1024) , httpapi::ChatMessage::ContentType::Image);
			subscription = m_client->subscribeSendChatMessageUpdates(ChatMessageRequest(1, totalSize, blockIndex, message));
			qDebug() << subscription.get();
}
```

Then the error shown in the figure below appears.

![image](https://user-images.githubusercontent.com/39958403/113728593-cf757700-9728-11eb-9194-e2c631af387c.png)

**Comment by semlanik** [comment]
Hi @tangyoha , it's an interesting question. First of all, I don't think that you really need to take care of sending a file by parts if you ensure that it fits the memory and the QByteArray requirements. The reason for this the HTTP2 proto basics. So HTTP2 will cut the message by parts implicitly. Another problem files that hard to fit into the memory immediately. For this, you would probably need to make a Message that stores some file part metainformation. I'll back with the solution later today.

**Comment by tangyoha** [comment]
I successfully sent large files with the generated API interface, about 4mb. It's okay. But if you can't send successfully with a simple chat program in the example, why does grpc not support sending large files at a post?

**Comment by tangyoha** [comment]
Hi @semlanik , I successfully sent large files with the generated API interface, about 4mb. It's okay. But if you can't send successfully with a simple chat program in the example, why does grpc not support sending large files at a post?

**Comment by tangyoha** [comment]
Hi @semlanik , In the client test file, I found that there is no testMethodClientStream service test, how to use the api generated by qtprotobuf?

**Comment by semlanik** [comment]
Hi @tangyoha , the problem with sending huge messages is currently on the server side. I found out that most gRPC server implementations have message size limits. So by default, it's 4MB. I scheduled a similar feature for QtGrpc. Meanwhile, the correct way to send huge files through gRPC is the definition of the own file transfer protocol, e.g.:

```
message FileChunk {
    uint32 sessionFileUID  = 1;
    uint32 num = 2;
    uint32 total = 3;
    bytes content = 4;
}

message None {
}

rpc sendFile(FileChunk) returns (None) {}
```
So the file should be cut into chunks on the sender side and glued back on the recipient side programmable, without gRPC involved.

**Comment by semlanik** [comment]
> Hi @semlanik , In the client test file, I found that there is no testMethodClientStream service test, how to use the api generated by qtprotobuf?

That's a good point, I omitted testing of the client streams since their implementation in QtGrpc is the exact same as regular methods. So the usage is the same as for testMethod. I don't plan to change this in nearest releases.
