### ISSUE TITLE
Converting proto enum to string

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#216]
In QML land, I'm accessing a QtProtobuf generated object instance.  One of its data members is a protobuf enum, and I wish to convert the value of this member to the string given in its definition, much as you would do with
```c++
   QString enum_name = QVariant::fromValue(enum_val).toString();
```
in C++ land, after including `Q_ENUM()` just like you're already doing in the generated `.h` file.

The alternative that I can see is for me to produce a simple helper class in C++ that would do this, but I do wonder if it could be added to the generated code somehow too ...

**Comment by semlanik** [comment]
I also dig into this direction a few weeks ago but left this task as something minor. But agree that this would be quite useful.

**Comment by semlanik** [comment]
I think this should be a part of some Qt Core(I didn't check, perhaps it's already there) or even each project should implement this it self. Short code snippet:
```cpp
<any place in the users code>
...
template<typename T,
         typename std::enable_if_t<std::is_enum<T>::value, int> = 0>
QString enumToString(T v) {
    return QVariant::fromValue(v).toString();
}
...
```

**Comment by gmabey** [comment]
Hmm — but it needs to be Q_INVOKABLE in order to get it from QML land, right??

**Comment by semlanik** [comment]
This still might be done using a qml-scope singleton class, that has appropriate method that can convert any(not only generated by QtProtobuf) enum, without the need to encapsulate the logic into each protobuf message.
