### ISSUE TITLE
problem using .pri files

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#222]
I'm on today's `master` branch, and after building and installing `.deb`'s, I see 
```bash
$ dpkg -L libqtprotobuf-dev
...
/usr/lib/x86_64-linux-gnu/cmake/QtProtobuf/protobufquickpluginTargets.cmake
/usr/usr
/usr/usr/lib
/usr/usr/lib/x86_64-linux-gnu
/usr/usr/lib/x86_64-linux-gnu/qt5
/usr/usr/lib/x86_64-linux-gnu/qt5/mkspecs
/usr/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules
/usr/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_grpc.pri
/usr/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_protobuf.pri
```
That is, I'm adding the switch `cmake .. -DCMAKE_INSTALL_PREFIX=/usr` and then the `.pri` files' path ends up with an *extra* `/usr` in front -- like `CMAKE_INSTALL_PREFIX` is being prepended when in fact nothing should be.

However, there seems to be one more issue, even after fixing the path to the `.pri` file -- it tries to link `/usr/lib/x86_64-linux-gnu/libQtProtobuf.a` instead of `/usr/lib/x86_64-linux-gnu/libQt5Protobuf.a`.  This is all on ubuntu 20.04

**Comment by gmabey** [comment]
Hello, I'm just now trying 0.6.0 and am still seeing the same issue with the .pri files, in that it's still trying to link to `/usr/lib/x86_64-linux-gny/libQtProtobuf.a` instead of `.../libQt5Protobuf.a` ... but I can see that `libQt5Protobuf.a` is definitely being included in the `.deb` file!

**Comment by semlanik** [comment]
I fixed the issue under the release commit. Packages are re-uploaded.

**Comment by gmabey** [comment]
Thank you for the update!  I've built and installed `master` but it looks like it's still 0.6.0 -- I don't know what it would take to give it a version 0.6.1, but it seems like that would be appropriate, given that it's a bug fix -- do you agree?

**Comment by semlanik** [comment]
I didn't get if the issue is fixed for you on master or not. If yes, then 0.6.0 includes the fix, since I don't see the reason to keep broken release packages. If not, then I will try to re-upload 0.6.0 again with fixes.

**Comment by gmabey** [comment]
Unfortunately, it does not seem to be fixed -- I can see in the linker line that it's still attempting to `-lQtProtobufWellKnownTypes` instead of `-lQt5ProtobufWellKnownTypes` even though it is correctly listing `libQt5Protobuf` ... as if it were fixed for the one but not for the other ...

I agree that there's no good reason to keep around a broken 0.6.0, but to me it seems that for bug traceability it would be helpful to increment the patch level (3rd digit) in the version number, like I think that's precisely *why* it has 3 digits.

**Comment by semlanik** [comment]
Could you please show the generated .pri files?

**Comment by semlanik** [comment]
Oops I think I lost the point that you're expecting Well-known types accessible using qmake. Hm, perhaps I'm wrong, but I don't remember if I implemented this.

**Comment by gmabey** [comment]
yes, you're right!  It's not supported with the `.pri` files -- instead, I was explicitly adding it to `LIBS` ... with the wrong name.  And `qmakeexample` now works, so please do consider this issue closed, and thank you.

**Comment by semlanik** [comment]
I guess then #227 makes sense :)
