### ISSUE TITLE
CMake script problems

### ISSUE THREAD

**Issue by lubagov** [semlanik/qtprotobuf#238]
**Describe the bug**
If the QT_PROTOBUF_NATIVE_GRPC_CHANNEL option is enabled, that is, only 2 header files, after installing qgrpcchannel.h and QGrpcChannel, other header files from the QtProtobufGrpc directory are not included in the installation. I'm not very good at CMake scripts, but it seems that the qt_protobuf_internal_extend_target function, instead of adding new ones, overwrites the values and the old ones are deleted.

**To Reproduce**
set `-DQT_PROTOBUF_NATIVE_GRPC_CHANNEL=ON` in CMake args.

**Environment:**
Ubuntu 18.04, CMake 3.18.4

**Comment by semlanik** [comment]
It's definetly a bug, and I already have a fix candidate, but meanwhile, I found out that there is AUTOMOC issue that blocks me from submitting a fix.
