### ISSUE TITLE
repeated enum is not accessible from QML

### ISSUE THREAD

**Issue by pritamghanghas** [semlanik/qtprotobuf#255]
*Question*
If I create a repeated field with enum type. Such a list always shows up as undefined on the QML side. Doesn't matter how you return it.

eg.
enum JobState {
        S_UNSPECIFIED = 0;
        S_INIT = 1;
        S_STARTED = 2;
        S_DONE = 3;
        S_FAILED = 4;
}

message Job {
    string job_id = 1;
    repeated JobState state_history = 2;
}

stateHistory will result in undefined on qml side.

**Comment by gmabey** [comment]
I have had the exact same issue; my workaround was to convert it to a `QList<int>` in C++ and populate it as a separate property of that C++ class.

P.S. I'm working from this fork ... https://github.com/gmabey/qtprotobuf

**Comment by pritamghanghas** [comment]
@gmabey I did the same, but looking at QtProtobuf code, I couldn't understand why exactly is this happening.

**Comment by semlanik** [comment]
@pritamghanghas it was regression from https://github.com/semlanik/qtprotobuf/pull/187. Non-message list properties should not generate add the Data suffix to their property names.
