### ISSUE TITLE
simplechat client requires restart after authentication failure

### ISSUE THREAD

**Issue by eugmes** [semlanik/qtprotobuf#259]
**Describe the bug**
simplechat example client does not seem to send credentials to the server after entering password incorrectly once. A restart is required to enter new credentials

**To Reproduce**
1. Run simplechatserver example
2. Run simplechat example
3. Enter invalid credentials, observe an `Authentication failed` message in the server output.
4. Try entering other credentials in the client, the server does not print any messages this time.

**Expected behavior**
It should be possible to retry entering credentials in the client without a restart.

**Environment:**
 - OS: Debian unstable
 - Version eb1a8b55287b0c41f5ed58dd407681ede4ace5cd, built with all 3rd party submodules

**Additional context**

The client prints these messages to console:

```
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
qrc:/main.qml:113:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qtprotobuflog: "messageList" call "qtprotobuf.examples.SimpleChat" stream finished:  "Невідома помилка"
```

The last message translates "Unknown error".

**Comment by semlanik** [comment]
Thanks! There are couple issues in gRPC stream implementation. I need to complete the refactoring one day.
