### ISSUE TITLE
Make message generation configurable

### ISSUE THREAD

**Issue by caashableRamOoOo** [semlanik/qtprotobuf#275]
**Problem description**
First of all, thanks for the contribution to the Qt community, u've got urself a real time saving tool right there.
The issue:
Messages code generation is statically defined, cannot add features to the generated code.

**Suggestion/solution**
Add more granularity to the message generation process by doing the following:

- Externalize some of the usefull strings defined in template.h to a json and get rid of the ones that does contain  code unit,such as a bloc, a semi bloc, a prototype ...
- Implement specialized printers for each features of a C++ Class that wraps the code units allowing to alter prototypes and bloc content as required by the user by adding more or less entries to the json.
- Use a factory to populate the message class using the aforementioned json as a configuration file and the specialized printer as populators

**Additional context**
Some like the following should do:

 Message* Factory::create(Factory::Features key,  Message* message, QJsonObject configuration);

where Factory::Features would contain some like the following:
enum Features
    {
        Constructor,
        Setter
        Getter
        Field
        ...
    };

if u're down in having this capability in the project  i could propose a quick generic implementation once u hand me the collaborator rights (just hand them to me regardless )

**Comment by semlanik** [comment]
This is very ambitious suggestion, I would love to see this in the reference protobuf generator. But from qtprotobufgen it will be hard to test the generated code in all possible scenario, and would add code incompatibility in many scenarios.  I agree that current generator is far from ideal, but by making it customizable, it only cultivates entropy.

**Comment by caashableRamOoOo** [comment]
Ok,  closing this issue ... ^^
