### ISSUE TITLE
protobuf and grpc versions

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#4]
How hard are the version requirements on protobuf (3.6.0) and grpc (1.15.0)?
I ask because I'm trying to make qprotobuf work on the NVIDIA Jetson Nano, and there's no good way (that I've found so far) to upgrade it beyond Ubuntu 18.04, which includes protobuf 3.0.0 and grpc 1.3.2 .  My attempts to compile them from source have been frustrated -- in the compilation of grpc there's a compile error similar to what's described in https://github.com/facebook/folly/issues/1098 but without the option of exercising that OP's fix.
I've also tried making gcc8 the default -- that didn't help either.
I think that gprotobuf 3.6 is not going to be a problem; I think it's just grpc.  

Are there specific grpc-1.15.0 features/fixes that are needed for qtprotobuf?

**Comment by gmabey** [comment]
Ok, looks like grpc-1.3.2 and protobuf 3.0.0 do work -- sorry I missed the note about older versions.

**Comment by semlanik** [comment]
Yep, pointed in README versions are only that we tested. Other might work also
