### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Bowfish** [semlanik/qtprotobuf#5]
When I compile the project according to your instructions I get the following error

```
simpletest.cpp:(.text._ZN19qtprotobufnamespace5tests20StepChildEnumMessageD2Ev[_ZN19qtprotobufnamespace5tests20StepChildEnumMessageD5Ev]+0xf): undefined reference to `vtable for qtprotobufnamespace::tests::StepChildEnumMessage'
collect2: error: ld returned 1 exit status
gmake[2]: *** [tests/test_protobuf/CMakeFiles/qtprotobuf_test.dir/build.make:167: tests/test_protobuf/qtprotobuf_test] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:583: tests/test_protobuf/CMakeFiles/qtprotobuf_test.dir/all] Fehler 2
gmake: *** [Makefile:141: all] Fehler 2
```
Do you have an idea what I'm doing wrong?

Thanks for your help

**Comment by semlanik** [comment]
It seems mock was not generated correctly. Could you please provide your build environment info? and probably full build log as attachment

**Comment by Bowfish** [comment]
Where can I find these information? I'm not very familiar with cmake.

**Comment by Bowfish** [comment]
Now I found the files. See attached.
[CMakeError.log](https://github.com/semlanik/qtprotobuf/files/3799075/CMakeError.log)
[CMakeOutput.log](https://github.com/semlanik/qtprotobuf/files/3799076/CMakeOutput.log)
[CMakeRuleHashes.txt](https://github.com/semlanik/qtprotobuf/files/3799077/CMakeRuleHashes.txt)
[TargetDirectories.txt](https://github.com/semlanik/qtprotobuf/files/3799079/TargetDirectories.txt)

**Comment by semlanik** [comment]
Hi, I meant the full build logs. So you could do that:
mkdir build
cd build
cmake .. > cmakelog 2>&1
make VERBOSE=1 -j4 > buildlog 2>&1

Once finished with error, please attach 'cmakelog' and 'buildlog' from 'build' directory

**Comment by Bowfish** [comment]
Hi. Attached you can find the files.

[build.log](https://github.com/semlanik/qtprotobuf/files/3800308/build.log)
[cmake.log](https://github.com/semlanik/qtprotobuf/files/3800309/cmake.log)

**Comment by semlanik** [comment]
Now I see different error. It seems Qt private headers are not installed. I will make explicit check for this in CMakeLists. Please install Qml private headers

**Comment by semlanik** [comment]
Also pull latest master I add explicit check for private headers

**Comment by Bowfish** [comment]
How can I install the private headers?

**Comment by Bowfish** [comment]
I installed them. Now I get some other errors.
[cmake.log](https://github.com/semlanik/qtprotobuf/files/3800364/cmake.log)

**Comment by semlanik** [comment]
It depends on how you perform Qt installation. If you did it using qt-installer/qt-online installed, it should be availble here <path_to_qt_installation>/<version>/gcc_64/include/QtQml/<version>/QtQml/private. If you use system qt check how install qt private headers in your distribution

**Comment by semlanik** [comment]
> I installed them. Now I get some other errors.
> 
> [build.log](https://github.com/semlanik/qtprotobuf/files/3800365/build.log)
> [cmake.log](https://github.com/semlanik/qtprotobuf/files/3800364/cmake.log)

Please clean your build directory and run build from beginning.

**Comment by Bowfish** [comment]
I managed to install them. Now I get some other errors.

[cmake.log](https://github.com/semlanik/qtprotobuf/files/3800380/cmake.log)
[build.log](https://github.com/semlanik/qtprotobuf/files/3800381/build.log)

**Comment by Bowfish** [comment]
I did that. Here are the new logs
[cmake.log](https://github.com/semlanik/qtprotobuf/files/3800384/cmake.log)
[build.log](https://github.com/semlanik/qtprotobuf/files/3800385/build.log)

**Comment by semlanik** [comment]
It seems parsemessages.go didn't work correctly. Do you have golang installed in system?

**Comment by Bowfish** [comment]
Yes. golang is installed.

**Comment by semlanik** [comment]
For now I could suggest to enable all-in-one build by running
git submodule update --init --recursive

And run clean build again

**Comment by Bowfish** [comment]
No it complied without errors, but when I run ctest I get the following output:

```
Test project /home/damian/src/qtsrc-5.13/qtprotobuf/build
    Start 1: qtprotobuf_test
1/4 Test #1: qtprotobuf_test ..................   Passed    0.02 sec
    Start 2: qtgrpc_echo_test

2/4 Test #2: qtgrpc_echo_test .................   Passed   80.13 sec
    Start 3: qtgrpc_secure_test
3/4 Test #3: qtgrpc_secure_test ...............   Passed    5.98 sec
    Start 4: qtprotobuf_qml_test
4/4 Test #4: qtprotobuf_qml_test ..............***Failed    0.12 sec

75% tests passed, 1 tests failed out of 4

Total Test time (real) =  86.26 sec

The following tests FAILED:
          4 - qtprotobuf_qml_test (Failed)
Errors while running CTest
```

Can I also use your library in a qmake project? If yes, how do I have to do that?

**Comment by semlanik** [comment]
For tests it's ok, because required bug fix is still not integrated in Qt.

qmake is not supported yet as it is. But you could install libs in your system and use it as any 3rdparty library in your qmake projects.

**Comment by Bowfish** [comment]
Ok. Thank you very much for your help. You did a great job.

**Comment by semlanik** [comment]
In any case I will check what is probably missed, according to you issue. Could you please provide some input about your operating system and versions of golang, protobuf, grpc installed in system?

**Comment by Bowfish** [comment]
opensuse linux x86_64
go version go1.12.12 linux/amd64
libprotoc 3.9.1
grpc 1.23.1-2.1

**Comment by Bowfish** [comment]
Do you have any documentation on how to use the library?

**Comment by semlanik** [comment]
Mainly you could follow README and examples. But also there are some doxygen based docs that could be generated. Instructions for doxy generation are in README as well.

**Comment by semlanik** [comment]
It seems build is ok. please look at docker based build procedure and install all required packages
