### ISSUE TITLE
Simplify Qt protobuf type registration

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [semlanik/qtprotobuf#55]
A while ago, I reported issues with statically registering Qt protobuf types due to "Static Initialization Order Fiasco." In response to that report, you removed automatic registration and replaced it with the "qRegisterProtobufTypes" function in qtprotobuf_global.qpb.h that can be called manually by the developer. The main problem with this approach for Windows developers (who often do not use CMAKE for VS projects) is that _only the last processed type_ shows up in qRegisterProtobufTypes if the .proto files are processed manually with "protoc." So, such developers (including me) are forced to manually add qRegisterProtobufType<...>() call for each new type. Here is the better way which avoids _both_ issues:

1) Define static namespace to hold type registration function lambdas for the types:

a) QtProtobufRegister.h

```
namespace QtProtobufRegister
{
	typedef std::function<void(void)> RegisterFunction;

	void Init();
	QList<RegisterFunction>& GetList();

	template <class T>
	struct Type {
		Type(RegisterFunction initializer)
		{
			GetList().append(initializer);
		}
	};
};
```
b) QtProtobufRegister.cpp

```
#include "QtProtobufRegister.h"

namespace QtProtobufRegister
{
	QList<RegisterFunction>& GetList()
	{
		static QList<std::function<void(void)>> registrationList;
		return registrationList;
	}

	void Init()
	{
		for (auto registerFunc : GetList())
		{
			registerFunc();
		}
	}
}
```

2) For generated code, add the following static variable to the class CPP file (inside namespace but before the class definition):

```
    static QtProtobufRegister::Type<{CLASS_TYPE}> s_protobufRegister([](){
        qRegisterProtobufType<{CLASS_TYPE}>();
    });
```
3) When it is finally safe to register the Qt types, a developer can simply call the following to register _all_ Qt Protobuf types all at once:

`QtProtobufRegister::Init();`

The way this works is for every class its registration call is _not_ performed immediately when the class is loaded statically - but rather is stored in the list. When 'QtProtobufRegister::Init()' is caller - all registration function from that list are executed, avoiding the Static Initialization fiasco.

I've successfully used a similar approach to register over 100 QML types in our application.

Another advantage is that you can drop "qtprotobuf_global.qpb.h" file as redundant.

**Comment by semlanik** [comment]
I like this approach, will integrate shortly
