### ISSUE TITLE
Invalid Field Naming in Generated Qt Class (different names in H and CPP)

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [semlanik/qtprotobuf#6]
The generator does not handle field names with "_" correctly and generates different names in ".h' and ".cpp" output files - causing compiler failure.

For example, consider this proto:

```
syntax = "proto3";

package test;

message Test
{
	string some_field = 1;
}
```

Output contains these lines in ".h":

```
private:
    QString m_someField;

```
While ".cpp" contains:

```
Test::Test(const QString &some_field, QObject *parent) : QObject(parent)
    , m_some_field(some_field)
{
}
```

Note the difference in field naming (**m_someField** vs **m_some_field**).

P.S. It would be great to be able to _select the naming convention_ of the output somehow - so that the output will match VS formatting used by the developer.

**Comment by semlanik** [comment]
e0c89b7ece18445f56378d248e7f3e04b02879c9
