### ISSUE TITLE
Add QML registration

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [semlanik/qtprotobuf#60]
At the moment Qt Protobuf output provides a convenient way to register Qt types through qRegisterProtobufTypes. However, to make the types available to QML, qmlRegisterType has to be still manually called for each new type.

Could you add QML type registration to qRegisterProtobufTypes as well?

Thanks,

Michael

**Comment by R0ll1ngSt0ne** [comment]
P.S. This could be optional through proviging a separate **qml**RegisterProtobufTypes

**Comment by semlanik** [comment]
@R0ll1ngSt0ne it's already done. You may use `QT_PROTOBUF_OPTIONS` environment variable for protoc command:
```bash
QT_PROTOBUF_OPTIONS=QML protoc --plugin=protoc-gen-qtprotobuf=<path/to/bin>/qtprotobufgen --qtprotobuf_out=<output_dir> <protofile>.proto
```

Probably it's good practice to inverse this variable to NOQML and generate qml registration and code by default. Will provide pull request with related changes, please let me know if it's better

**Comment by R0ll1ngSt0ne** [comment]
@semlanik: thanks, somehow I missed that option - sorry.

**Comment by semlanik** [comment]
@R0ll1ngSt0ne, so probably it makes sense to merge https://github.com/semlanik/qtprotobuf/pull/61, that enables QML by default

**Comment by semlanik** [comment]
Declined idea to enable QML by default. Added extra paragraph to README
