### ISSUE TITLE
"Static Initialization Order Fiasco" with QProtobufRegistrationHelper

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [semlanik/qtprotobuf#7]
The generator produces this "helpful" piece of code in the output:

`static QtProtobuf::QProtobufRegistrationHelper helper(registerTypes);`

This  static variable often leads to crash on startup when running VS-compiled executables, due to well-known "static order initialization fiasco":

https://stackoverflow.com/questions/41938297/calling-qmlregistertype-in-the-registered-class-on-debug-crashes-application

Basically, at the time QProtobufRegistrationHelper tries to register the type, the type's static metadata has not been created yet - causing the crash (since the order is indeterminate).

Suggestion - do not attempt to call registerTypes() statically.  Instead, provide a static method and leave the decision up to a  developer to execute when appropriate

Better suggestion - store pointer to each registerTypes() in a static list. Provide static function to call all functions on the list at the time of developer's choosing.

**Comment by semlanik** [comment]
Yes it was discussed previously internally, thanks to pointing this issue explicitly. And I agree that it's better approach. But not sure when this refactoring will be done.

**Comment by R0ll1ngSt0ne** [comment]
Can we at least disable the mandatory static registration for the time being, as it causes the applications to crash and makes the generator unusable for Visual Studio development?

**Comment by semlanik** [comment]
1990f3caccc38fd62c3da39dfa09cd095b7ab103
