### ISSUE TITLE
enhancement suggestion for README.md

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#77]
```
diff --git a/README.md b/README.md
index ddbae71..f8c4233 100644
--- a/README.md
+++ b/README.md
@@ -84,6 +84,7 @@ Download and install:
 - GoLang 1.10 or higher [4](https://golang.org/dl/)
 - Yasm 1.3 or higher [5](http://yasm.tortall.net/Download.html)
 - Actual Visual Studio Compiler with cmake support that required by Qt [6](https://visualstudio.microsoft.com/downloads/)
+- protobuf 3.6.0 or higher [7](https://github.com/protocolbuffers/protobuf/releases) -- pick the protobuf-cpp-X.Y.Z.zip -- unzip it to a convenient place, then follow the instructions in cmake/README
 
 >**Note:** All applications should be in PATH
```

**Comment by gmabey** [comment]
never mind ... still struggling to get this windows build to work ...

**Comment by semlanik** [comment]
@gmabey what is your issue with Windows build? probably I could help. Overlall for Windows you don't need to copy protobuf manually. Please use submodule already integrated into project.

**Comment by gmabey** [comment]
Thanks for reopening the issue.  I'm not very fluent in Windows -- attached is the output I'm currently getting from cmake.

Thanks, Glen
[cmake_output.txt](https://github.com/semlanik/qtprotobuf/files/4119543/cmake_output.txt)

**Comment by gmabey** [comment]
Oops I didn't intent to close the issue ...

**Comment by semlanik** [comment]
Hi @gmabey I'm kindly sorry for delayed response. Your PATH simply lack of yasm binary. You need to download yasm, recommended url in README and add path to binary to  system PATH variable.

**Comment by gmabey** [comment]
Thank you @semlanik I was able to resolve my yasm problem.  Next failure attached ...
[path.txt](https://github.com/semlanik/qtprotobuf/files/4131310/path.txt)

**Comment by semlanik** [comment]
Hi @gmabey, this should be fixed in this commit ea043108db56e4ac127a51c42480743c72ca8410 at line 141

**Comment by gmabey** [comment]
Hmm -- I grabbed that commit but I'm still hitting the same error.

**Comment by semlanik** [comment]
Probably clean build required
