### ISSUE TITLE
Add support for Qt-centric less-well-known types

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#78]
There is no standard UUID message distributed with protobuf.  However, it would be really nice to be able to automatically convert a message member to a QUuid, don't you agree?

This may entail distributing a set of .proto files with qtprotobuf, that, *if* used as part of the user's .proto-defined messages, would get automatically translated that way.

**UPD by @semlanik:**
Following types will be added as less-well-known types:

- [x] QUrl
- [x] QChar
- [x] QUuid
- ~QLocale~ - Not unified
- [x] QColor

- [x] QDate
- [x] QTime
- [x] QDateTime

- [x] QSize
- [x] QSizeF
- [x] QRect
- [x] QRectF
- [x] QPolygon
- [x] QPolygonF
- [x] QPoint
- [x] QPointF

- [ ] QImage
- ~QPixmap~ - is internal Qt representation of image. Not sure if applicable to transfer it using protocol buffers
- ~QIcon~ - not something that has own data.
- ~QBitmap~ - inherited of QPixmap

- [ ] QQuaternion
- [x] QTransform
- ~QMatrix~ - Deprecated by Qt.
- [x] QMatrix4x4
- [x] QVector2D
- [x] QVector3D
- [x] QVector4D
- ~QEasingCurve~ - skip for now. Will add by request. It seems this field should be of google.protobuf.Any type

**Comment by semlanik** [comment]
Hi @gmabey nice idea, it would be nice to have list of desired types. Well-known types are not complete yet. Qt types cast/converters will be developed later on. But I think this feature might be useful

**Comment by semlanik** [comment]
Decided to make mappings for some meta types before QMetaType::UserType. Will add list to initial description

**Comment by semlanik** [comment]
Hi @gmabey, I complete basic implementation of less-well-known types. Mainly I decided to make it simple QtTypes instead. Documentation and usage examples are still in progress, but you could try it based on examples available it tests:

- https://github.com/semlanik/qtprotobuf/commit/d7520ee69c6f52e4589ec6ac45344a75c176ae2f#diff-52766bd6b6b9e03d55d7c97dd2910efe

- https://github.com/semlanik/qtprotobuf/commit/d7520ee69c6f52e4589ec6ac45344a75c176ae2f#diff-d0b16d1e3a949d54bc50761ac3116f96

Will complete implementation next week.

**Comment by gmabey** [comment]
Excellent!  Thank you for pushing this through, it will make some things easier.

A couple of comments on your structures ... of course the critical thing here was all of the infrastructure that you put in place to handle all of these conversions seamlessly, but consider this implementation details.

* For `QTime`, did you consider using simply a single `sint32` that would represent msecsSinceStartOfDay()?  It's more compact, but more importantly, it doesn't leave as much room for illegal values being deserialized.  Similarly for `QDateTime` (milliseconds since the epoch) and `QDate` (Julian days).

* For serializing `QColor` in the way I currently handle this type, I just use a `string` mostly so that I can preserve the intuitiveness of `steelblue` or whatever natural name there is for a color.  And `#RRRRGGGGBBBB` still works.  However, this also opens the door for the illegal values (strings that don't succeed in `setNamedColor()`) that I suggested you close with `QTime` ... More importantly, in serializing an already-existing `QColor`, you really have no way of knowing whether it was set with a natural name.  So, this comment is probably not the best suggestion, but I'll pass it along anyway and let you make the decision.

* Could you add a comment within `message QUuid` to document how it's stored, in case a non-QtProtobuf app (like, a python script) wants to write messages that use `QtCore.proto` messages?  My suggestion would be, WithoutBraces, but leaving the dashes in there (they make it more easily identifiable as a UUID) and also consider changing it from `string` to `bytes`.  That's what I've done in the mean time (before you implemented this feature) and I do actually have a case where the uuid is being generated by a python script for later display by a Qt gui.

* For `QRect` and `QRectF`, I've always had the impression that they internally use topleft and width-height (a `QSize{,F}`) instead of a bottomRight, but I haven't really checked that.  It does slightly simplify a check for illegal values, and with that mindset, all translations of the rectangle are valid.  I suggest you try to match the internal representation, whatever it is.

This is very exciting and I do appreciate all of your work on QtProtobuf!

**Comment by semlanik** [comment]
Hi @gmabey, lest go step-by-step

- Regarding QTime, I think it's good idea to use msec since start of day. So I will change implementation shortly.
- For QColor I don't think it's good idea to align it to color string. I know that most languages/frameworks have unified system of color naming. But nothing could be better than number based colors description. But good point is that color is limited by 4 bytes. So current representation is too bad. I made it based on existing constructor. Will change it to more applicable representation. Also it looks strange for me why Qt made it this way but put 0-255 limits in docs.
- For QRect I also thought about better representation, and I don't mind to make it as you defined. Probably 
```
message QRect {
   QPoint topLeft = 1;
   QSize size = 2;
}
```
Is the best for this. Will prepare changes later.

**Comment by gmabey** [comment]
yes, the new messages structure that you propose for `QRect` is exactly what I was thinking!
