### ISSUE TITLE
difficulty with fonts.googleapis.com

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#79]
Regarding the doxygen generated content -- it would make my life easier if there weren't any references to https://fonts.googleapis.com/ as it relates to stylesheets.  When that host can't be reached, it causes the page to load very slowly.

**Comment by semlanik** [comment]
Hi, probably I will put some fonts to github, later on if it's not contradict to license policies.

**Comment by semlanik** [comment]
171fb2940217f4d9e77d2f2d56476c9965449916
