### ISSUE TITLE
Output not following naming convention, breaking VS Custom Build Step

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [semlanik/qtprotobuf#8]
Any other protoc generator that outputs C++/C# code uses _name of the source file_ for the output file name, producing only one output source file for C# and a pair of H/CPP for C++.

For example, "security.proto" defining Account and Login messages would result in "security.**pb.h**" and "security.**pb.cc**" output files, containing both Account and Login classes.

qtprotobuf generates a pair of H/CPP for _each message_ and uses class name for naming each pair.

For example, the same "security.proto" from above results in "Account.cpp", "Account.h", "Login.cpp", "Login.h". 

Here are the problems with this approach:

1) It deviates from convention, producing confusion. It is no longer apparent which proto file produces a certain generated file - unless you go into code and search by name.

2) **It breaks custom build step** used by Visual Studio, since for proper cleanup/rebuild the step needs to know each output file name - which becomes a tedious manual work when there are multiple messages in a proto file. Adding a new message to existing proto file would involve going into custom build step setting for that proto file and manually adding names of the output files for the new message:

![image](https://user-images.githubusercontent.com/16037814/68420953-61133a80-016b-11ea-8ea3-6ce74cf796ce.png)

For a single pair of "pb.h" and "pb.cc" per proto file, custom build step output files can be generically specified as:
`$(InputDir)\$(InputName).pb.cc;$(InputDir)\$(InputName).pb.h`

![image](https://user-images.githubusercontent.com/16037814/68420911-5062c480-016b-11ea-953b-0f1e7b261930.png)

**Comment by semlanik** [comment]
Will discuss internally. But initial strategy was follow Qt guide lines as well. Probably I will make WIP commit this weekend and check if there are some issues related to this

**Comment by semlanik** [comment]
79db2ab057c603b730aea4f500502a7e4e1c7f91
