### ISSUE TITLE
documentation on using google's well-known types

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#80]
I'm now trying to include google.protobuf.Timestamp in a message, and I haven't been able to find anything in the documentation regarding special steps that [may] need to be taken in order for this to work.  Could you please elaborate a little on how that should be done?

**Comment by gmabey** [comment]
I'm getting a `bad_function_call` exception thrown from `QProtobufSerializerPrivate::serializeProperty()` -- it looks like the message member (a google.protobuf.TimeStamp) is not being found in the common set of handlers, so when handler.serializer() gets called, that exception is thrown.

I certainly am invoking `google::protobuf::Timestamp::registerTypes()` prior to this point in the code -- am I missing something else?

**Comment by semlanik** [comment]
Hi please look here:
bc17c3f94336e9bb4671c09293832a7de49a7b4f

Overall steps to get serialization work:
```
#include <qtprotobufwellknowntypes_global.qbp.h>
...

google::protobuf::qRegisterProtobufTypes();
qtprotobufnamespace::wellknowntypes::tests::TimestampMessage msg;
msg.serialize(someValidSerializerPointer);
```
