### ISSUE TITLE
compile failure when "package" is the same as a "message" name

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#82]
That is, within a .proto file -- when I make sure they are distinct, compilation succeeds.  I'm not sure whether that's an issue in the standard protobuf generator ...

**Comment by semlanik** [comment]
Please attach logs and samples, but I have feeling that it's standard limitations

**Comment by gmabey** [comment]
Hmm -- I'm not able to reproduce the problem in a self-contained example ... I'm not that worried about it anyway, please disregard.  Like, there's more important and valuable things for you to spend your time on.
