### ISSUE TITLE
getting along with valgrind

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#86]
I'm running valgrind on my application to try to find the source of memory corruption that's going on.  I do not suspect qtprotobuf as the culprit, but the qtprotobuf-generated code is making the output from valgrind much harder to parse.

That is, I'm seeing very many valgrind warnings that read:
  `Conditional jump or move depends on uninitialised value(s)`
They refer to the generated setter methods that first test whether the value has changed, then conditionally updates the data member and emits a "changed" signal.  

Please consider this an enhancement not a bug, as qtprotobuf is working fine, actually great -- it's been extremely valuable.

**Comment by semlanik** [comment]
Will check later on, probably it make sense to fix this warning

**Comment by gmabey** [comment]
Passing the `--track-origins=yes` flag to valgrind, I now see that it's not a qtprotobuf issue -- it originates in the signal/slot mechanisms.
