### ISSUE TITLE
cmake fails 

### ISSUE THREAD

**Issue by gmabey** [semlanik/qtprotobuf#9]
Hello,
I have a freshly installed Ubuntu 19.10 VM and can't seem to get cmake to be happy ... see attached.
Glen

[cmake_stdout.txt](https://github.com/semlanik/qtprotobuf/files/3918611/cmake_stdout.txt)
[CMakeFiles.tar.gz](https://github.com/semlanik/qtprotobuf/files/3918614/CMakeFiles.tar.gz)

**Comment by semlanik** [comment]
Please make sure that golang is installed

**Comment by gmabey** [comment]
I'm sad to say that from the README.md, it looked like golang was only required for Windows builds ... I should have tried installing it before creating an issue ...

**Comment by semlanik** [comment]
It's basically issue of build procedure. It should explicitly notify you about missed golang dependency. So I will keep it until add this message and line to README :)

**Comment by semlanik** [comment]
0d04127eb21c14b35cba5a3e526f41e4ce96297f
