### ISSUE TITLE
How to register all classes with one command for qml?

### ISSUE THREAD

**Issue by FinchZ** [semlanik/qtprotobuf#95]
I have a very large proto files contained so many messages.
I need to use them in qml file.
Can I register them by one command?

**Comment by semlanik** [comment]
Hi @FinchZ, which version do you use?

Basically we made auto-registration of all messages linked to your project by:
```
QtProtobuf::qRegisterProtobufTypes();
```

But it's only accessible on master and will be available in **0.2.0 release** at end of February.

This will register all proto-types linked to you binary. Please keep in mind that you also need to be sure that QML code generation was enabled.

**For version 0.1.0:**
You can include "qtprotobuf_global.qpb.h" file and call appropriate qRegisterProtobufTypes() for your package namespace.

Hope it will help.

**Comment by FinchZ** [comment]
WOW! IT'S AWESOME!!!THANK YOU VERY MUCH!
