### ISSUE TITLE
QT_PROTOBUF_STATIC flag has no effect on Windows

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [semlanik/qtprotobuf#97]
**Describe the bug**
Using -DQT_PROTOBUF_STATIC=TRUE flag when configuring the project still produced dynamically linked DLL libraries at build

**To Reproduce**
1. Run the following command line on Windows:

_"C:\Program Files\CMake\bin\cmake.exe" .. -DCMAKE_PREFIX_PATH="C:\Qt\5.13.2\msvc2017\lib\cmake" -DCMAKE_INSTALL_PREFIX="..\install" -DCMAKE_DEBUG_POSTFIX=D -DQT_PROTOBUF_MAKE_TESTS=FALSE -DQT_PROTOBUF_MAKE_EXAMPLES=FALSE -DQT_PROTOBUF_STATIC=TRUE -G "Visual Studio 16 2019" -A Win32_

2. Open the resulting SLN project and compile it
3. Take a look at output. It contains small import library "QtProtobuf.lib" and accompanying "QtProtobuf.dll" - no static library

**Expected behavior**
Resulting output should contain statically linked "QtProtobuf.lib" (about ~5MB size) and no DLL

**Environment:**
 - OS: Windows 10

**Additional context**

> **Note:** Please attach sample code to reproduce issue if applicable

**Comment by semlanik** [comment]
**Please pay attention that you need manually add definition of QT_PROTOBUF_STATIC in your project.**
